### ISSUE TITLE
analysis repetition loop

### ISSUE THREAD

**Issue by spoo333** [DarwinAwardWinner/rganalysis#1]
With certain files rganalysis (or some of the backends?) insists on re-analysing them even though they already have replaygain info in the tag. The analysis always completes without any issues, however next time rganalysis re-analyses those files. I've tried re-converting the audio files - always the same result. This is not a real problem, however it slows down the analysis process.

**Comment by DarwinAwardWinner** [comment]
Can you give me an example file along with the command that you used to run rganalysis so that I can test this bug on my own computer?

**Comment by spoo333** [comment]
The command I use is `rganalysis -m --low-memory -b bs1770gain -j1 -g auto [directory]`. I'll upload some files later and email the link to your private address.
In one case - a flac album of 13 tracks with track 11 being a silent "gap" track - deleting track 11 solved the issue.

**Comment by spoo333** [comment]
Not comment but command ;-)

**Comment by spoo333** [comment]
I've sent you the link to the files

**Comment by DarwinAwardWinner** [comment]
I'm sorry, I don't seem to have gotten the email. Did you send it to the address listed in my Github profile?

**Comment by spoo333** [comment]
I sent it from dave@kraisch.com. will send it again.
David

**Comment by spoo333** [comment]
I sent it to rct@thompsonclan.org on Thursday. I didn't want to post the
file link here. Let me know if you received it

**Comment by spoo333** [comment]
I've sent it to rct+github@thompsonclan.org now.

**Comment by DarwinAwardWinner** [comment]
For some reason I'm not receiving your emails. The last one I have is from your address is August 11.

**Comment by spoo333** [comment]
Can you check again? I've resent it

**Comment by DarwinAwardWinner** [comment]
Still nothing, I'm afraid.

**Comment by spoo333** [comment]
That's odd. I've sent it again from another address

**Comment by spoo333** [comment]
Anything by now?

**Comment by DarwinAwardWinner** [comment]
Ok, I received that one, although I had to fish it out of the spam trap.

**Comment by spoo333** [comment]
Great, and shame about the spam issue. It's happened before...

**Comment by DarwinAwardWinner** [comment]
Ok, I've spotted the problem. When a track is especially quiet, it will get a gain value of exactly zero, which evaluates to false in Python, making my program believe that there is no replaygain tag. So I just need to add code to distinguish between a false value and an empty value.

**Comment by spoo333** [comment]
:-) great you could spot the issue that fast. I look forward to a future
update of the script. Imagine I can remove the shared audio files online?

**Comment by DarwinAwardWinner** [comment]
Can you leave them there until I've had a chance to test the fix on all of them? It's always possible there's a second bug lurking in the code.

**Comment by spoo333** [comment]
Sure. Also, if you need more files to test, I've got three more albums
(albeit huge ones in size) that the script currently 'dislikes'. Or you let
me know when the new code is ready and I'll run tests on my system.
Thanks

**Comment by DarwinAwardWinner** [comment]
Fixed by bf9e833 in version 3.4.

**Comment by spoo333** [comment]
Thank you. All files including the large ones are fine now.
