### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by alidaf** [DarwinAwardWinner/rganalysis#3]
I'm afraid I seem to have another issue.

I've run it around 6 times but it freezes at around 2-3% but never on the same album. There is no continuous progress bar, instead it scrolls up and shows a new progress bar for the current scan. I've tried both back-ends but both have the same effect.

I've tried using -m to reduce memory but it only appears to use around 25% anyway.

I've tried it with -v as well but there is no other information at the time.

Any ideas?

**Comment by alidaf** [comment]
It has something to do with the jobs switch. Switching it off with -j 1 seems to be a workaround. I'll just use that for now.

**Comment by DarwinAwardWinner** [comment]
Could you give me an example log of what it looks like when the freeze happens, up to the point where you cancel it?
