### ISSUE TITLE
'Could not find any usable backends.'  ----  only -h works

### ISSUE THREAD

**Issue by karolzlot** [DarwinAwardWinner/rganalysis#8]
Any clue?

build installed via readme method:

	pi@raspberrypi:~/Desktop/muza $ rganalysis -h
	usage: rganalysis [-h] [-f] [-i] [-n] [-g (track|album|auto)]
					  [-b (audiotools|bs1770gain|auto)] [-j 4] [-m] [-q] [-v]
					  [music_dir [music_dir ...]]

	Add replaygain tags to your music files.

	positional arguments:
	  music_dir             Directories in which to search for music files.

	optional arguments:
	  -h, --help            show this help message and exit
	  -f, --force-reanalyze
							Reanalyze all files and recalculate replaygain values,
							even if the files already have valid replaygain tags.
							Normally, only files missing or inconsistent
							replaygain tags will be analyzed.
	  -i, --include-hidden  Do not skip hidden files and directories.
	  -n, --dry-run         Don't modify any files. Only analyze and report gain.
	  -g (track|album|auto), --gain-type (track|album|auto)
							Can be "album", "track", or "auto". If "track", only
							track gain values will be calculated, and album gain
							values will be erased. if "album", both track and
							album gain values will be calculated. If "auto", then
							"album" mode will be used except in directories that
							contain a file called "TRACKGAIN" or ".TRACKGAIN". In
							these directories, "track" mode will be used. The
							default setting is "auto".
	  -b (audiotools|bs1770gain|auto), --backend (audiotools|bs1770gain|auto)
							Gain computing backend to use. Different backends have
							different prerequisites.
	  -j 4, --jobs 4        Number of albums to analyze in parallel. The default
							is the number of cores detected on your system.
	  -m, --low-memory      Use less memory by processing directories one by one
							rather than pre-computing the complete list of files
							to be processed. This will disable progress bars, but
							will allow rganalysis to run on very large music
							collections without running out of memory.
	  -q, --quiet           Do not print informational messages.
	  -v, --verbose         Print debug messages that are probably only useful if
							something is going wrong.

----------------

	pi@raspberrypi:~/Desktop/muza $ rganalysis . -n
	Traceback (most recent call last):
	  File "/home/pi/berryconda3/bin/rganalysis", line 17, in <module>
		plac_call_main()
	  File "/home/pi/berryconda3/bin/rganalysis", line 11, in plac_call_main
		return plac.call(main)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/plac_core.py", line 330, in call
		cmd, result = parser.consume(arglist)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
		return cmd, self.func(*(args + varargs + extraopts), **kwargs)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/rganalysis/main.py", line 130, in main
		raise BackendUnavailableException("Could not find any usable backends.")
	rganalysis.backends.BackendUnavailableException: Could not find any usable backends.

----------------

	pi@raspberrypi:~/Desktop/muza $ rganalysis .
	Traceback (most recent call last):
	  File "/home/pi/berryconda3/bin/rganalysis", line 17, in <module>
		plac_call_main()
	  File "/home/pi/berryconda3/bin/rganalysis", line 11, in plac_call_main
		return plac.call(main)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/plac_core.py", line 330, in call
		cmd, result = parser.consume(arglist)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/plac_core.py", line 207, in consume
		return cmd, self.func(*(args + varargs + extraopts), **kwargs)
	  File "/home/pi/berryconda3/lib/python3.6/site-packages/rganalysis/main.py", line 130, in main
		raise BackendUnavailableException("Could not find any usable backends.")
	rganalysis.backends.BackendUnavailableException: Could not find any usable backends.
	pi@raspberrypi:~/Desktop/muza $ 

----------------

Currently on WIndows on my debug build I have the same situation:
 also `-h` works, 
and if not -h I have the same error:

 	File "c:\Users\fun\Dropbox\repos\GitHub\rganalysis\rganalysis\main.py", line 131, in main
		raise BackendUnavailableException("Could not find any usable backends.")
	rganalysis.backends.BackendUnavailableException: Could not find any usable backends.

**Comment by DarwinAwardWinner** [comment]
Did you see the note in the README about installing the prerequisites for one of the backends?

**Comment by DarwinAwardWinner** [comment]
I should improve that error message, though.

**Comment by karolzlot** [comment]
Now I see it ;-)
